
 spring:
   application:
     name: hystrixclient 
   rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
    
 server:
   port: 3332

 eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      


   
  
