spring:
  application:
    name: sleuth-ervice2
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest 
#  zipkin:
#    base-url: http://localhost:9411/
#    enabled: true
 
server:
   port: 9422
   