spring:
  application:
    name: feign-hystrix

server:
  port: 3331

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  rabbitmq:
    addresses: amqp://localhost:5672
    username: guest
    password: guest