spring:
  application:
    name: turbine
  rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
#  cloud:
#      stream:
#          rabbit:
#              bindings:
#                  test:
#                     consumer:
#                        prefix: z
#          bindings:
#               input:
#                   group: default

#turbine:
#   stream:
#      port: 8888
  
server:
  port: 3331
  

  
   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
                         
#turbine:
#   appConfig: feign-hystrix
#   clusterNameExpression: "'default'"













